<?php
$list_name = array(
'Diana Janes', 
'Jane Austin', 
'John Jones', 
'Kelly Albert', 
'Jim James',
'Carla Leda',
'Nina Joe',
'Dena James',
'Robert Green',
'Phil Joseph',
'Don Donohoe',
'Corey Brown', 
'Rosana Dimitri',
'Carl Dicken', 
'Janet Roberts',
'Barbara Williams',
'Tanya Lovado',
'Peter Gray',
'Dana Rita',
'Doggie Duck',
'Joe Alive',
'Dana Dina',
'Kathy Ferrara',
'Carlos Alberto',
'Melanie Jason',
'Angela Cadini',
'Katia Flavia',
'Robert Fillard',
'Kosta Constanci',
'Jennifer Presper',
'Iron Man'
);

$list_email = array(
'mj@yahoo.com', 
'chick_cool@aol.com', 
'j2001@google.com', 
'simpledude_1@bing.com', 
'crypt-J@jipps.com',
'robot-jack@pid.com',
'giga-beta@colone.com',
'dynamicHarry@timph.com',
'durangoBit@goodle.com',
'ympthyTangle@yahoo.com',
'credoJay@bing.com',
'Bope2007@ipanema.com',
'gerry_harrychick@yahoo.com',
'pitagoras@bing.com',
'riopic@gmail.com',
'jc_crickets@plc.com',
'terrace_strick@gmp.com',
'potomac_pc@ptc.com',
'forever_young@plb.com',
'superfast_123@imb.com',
'lateforwork@bing.com',
'darksideofthemoon@ibm.com',
'gitaclue@bca.com',
'tuvia@plc.com',
'treasure_rack@bac.com',
'tamidue@fetini.com',
'kcb@lenovo.com',
'home@filmard.com',
'jeanini@pillbc.com',
'visitus@ibm.com',
'calibri22@gmail.com'
);
?>